export default {
    karvatura: `Ilmeeni kun entinen koira kantoi aina karvatura koira kantoi sänkyyn kesällä hiekkaa kun makoili ja pyöri tarhassa jotka karisi sitten illalla sisälle kun otettiin koirat sisään.`,
    imppaus: `Ite oon impannut yhteensä varmaan kymmeniä tunteja ja oon 100% kunnossa vaikka oon impaanut varmaan 100 tuntiakin impannut`,
    hauskin: `Sieltä se tulee taas. Katsokaa kaikki! Hän postasi sen taas kerran! Eikö hän olekin koko laudan hauskin henkilö? Voi hyvä luoja!

    Voin kuvitella miten istut pimeässä huoneessa, ainonana valonlähteenäsi tietokoneen ruutu. Kikatat kuin pieni tyttö, kun teet taas kerran langan, mihin voit laittaa hienon trollausyrityksesi. Täytät captchan ja lähetät viestin. Tai ehkä et edes täytä captchaa. Ehkä olet oikeasti niin luuseri, että ostit kultatilin, jolloin vain liität trollailukansiosi helmen viestikenttään ja lähetät sen. Ja me kaikki tiedämme sen teeman. "AAH AAH AAAAHH", eikö vain? Voin kuvitella miten paljon naurat lähettäessäsi viestiä, niin että pudotat sipsusi lattialle, mutta se ei haittaa, koska äitisi käy siivoamassa huoneesi seuraavana päivänä. Niin tosiaan, unohdinko sanoa? Asut äitisi luona. Olet laiska paska ja hän on luultavasti kyllästynyt ainaiseen holhoamiseesi. Niin kyllästynyt aina tekemään kaiken aikuiselle miehelle, joka postaa trollauslankoja kaiket päivät satunnaiseen. Äitisi kuvitteli, että sinusta tulisi astronautti tai tiedemies, mutta rupesit työttömäksi rotaksi. trollauslankoja postaava rotta. Äitisi ei voi edes puhua sinulle, kun ainoa asia mitä osaat sanoa on "AAH AAH AAAAHH". Olet muuttunut parodiaksi omasta itsestäsi. Ja se on kaikki mitä tulet olemaan. Pieni, surullinen mies pimeässä huonessa postaamassa samaa teemaa päivästä toiseen. Ja se on kaikki mitä tulet olemaan.`,
    huutista: `Kun oon lueskellu tätä foorumia niin mua on aina ihmetyttäny tää tämmönen helvetinmoinen huutis, huutista huutista huutista... kaikennäkösille järkevillekin asioille tulee huutista miks pitää joka helvetin asialle tulla huutista Mun pitikin sanoa paljon törkeämpää tekstiä, mutta mä nyt siivosin tän ja niin edelleen mut on tää uskomatonta huutista, huutista joka helvetin asialle tulee huutista. Mitään hauskaa ei mul oo yhtään hauskaa kun ihan typerille asioille koko ajan tulee huutista. No huutista tulee joka ikiselle asialle eihän kukaan kestä lukee tämmöstä huutista`,
    proffa: `Minkälainen olisitte halunneet olla nuoruudessa jos nyt saisitte päättää? Minä tällainen:

    Lempinimi "Proffa". Hiukset kammattu siististi mutta semicooliin tyyliin. Kauluspaita rennosti ulkona suorista housuista. Istuskelisin skeitti rampilla ja loisin vaikutelman että oon hyvä skeittaan mutta en vaan jaksa, kommenteilla kuten "Hyvä Ripe, melkein onnistu 360, tsemiä!".
    
    Mäkissä tilaisin vaan mustan kahvin vahvana, ja seuraisin keskustelua. Välillä heittäisin väliin jonkun osuvan kommentin, ja muut olis että "hmm! ei ollakkaan tajuttu tota ennen!".
    
    Muijat pitäisi minua persoonallisena, hiukan salaperäisenä.`,
    tykitys: `True Kakkofonic Tykitys Metallia ovat bändit kuten Sonata Arctica, Pathfinder, Fairyland, Stratovarius, Gamma Ray, Dragonland ja Angra. Sinä voit kuunnella Morbosidadiasi jos tahdot, mutta et ymmärrä todellisesta hevanderista yhtään mitään. Olet pelkkä poseri ja voit painua vittuun koko skenestä. Tykitys Metal on Todellista musiikkia, jota ei ole tarkoitettu sinunlaisillesi eläimille, vaan todellisille hevi äijille, jotka eivät piittaa sinunlaisistasi pelleistä. Tykitys Metal on eliitin musiikkia ja sinä et sitä ymmärrä. Kukaan teistä ei ymmärrä Todellista Kakkofoniaa. Olette naurettavia pikkulapsia. Maailmankuvamme perustuu tribaalismiin, henkilökohtaisella tasolla tuplabasarismiin, kollektiivisella tasolla falsetismiin. Ilman ymmärrystä susipaidoista, on turha haaveilla ymmärtävänsä tykittämisen maailmankuvaa. Teistä kukaan ei voi ymmärtää tykitystä, sillä olette kaikki älyllisesti kuin kastematoja. Te ette voi yltää elitistisen Kakkofonian tasolle, joten miksi edes haaveilette siitä. Sudet ja Tykitys Metal ovat eliitille. Todellisille hevi äijille.`,
    päärynä: `kerran heitettii päärynä vitun lujaa seinään (Juuso heitti ja se käy salilla) niin kuulu vaa poks eikä ollu edes mitään mössö tai mitn missää vaa se hävis kokonaan`,
    vessapaperi: `>ole 19 >muuta omaan kämppään vihdoin >viisi päivää muutosta >pyyhi persettäsi viimeisillä paperijämillä porukoilta saadusta rullasta >samalla tajua, että vessapaperi on nyt loppu eikä tietenkään itsemurhayksiöstä löydy pillupuhelinta >tajua hiljalleen, että seuraavaksi minun pitää ostaa vessapaperia >voi henkisesti pahoin

    Vedin tästä eteenpäin pari viikkoa siten, että joka kerta kun kävin paskalla niin kävin myös puoliksi suihkussa, että perseeni peseytyisi kunnolla. Mietin joka kerralla sitä samaa asiaa, eli miten se ensikerta oikeasti tulee menemään. Välillä jopa nukkumaan kun yritti mennä niin pyöri vain päässä sen kassatytyn nauru sekä skenaariot kuten esim se, että viivakoodi mysteerisesti ei toimi sen vessapaperin kohdalla, sillä hetkellä sattuu olemaan juuri kiireistä ja sitten se joutuu räpläämään sitä vessapaperin viivakoodia erikseen, samalla kun takana on tietenkin lauma paikallisen lukion tytyjä. Tämän tyyppisiä skenaarioita pyöri aina toisinaan päässäni eikä niistä päässyt eroon. 
    
    Sitten tapahtui seuraavaa
    
    >puhelin soi <moi nyymi, joko sait kamas roudattua? >joo <no? >mitä? <eiks meillä ollu puhetta niistä laneista, sinä minä ja make? >ainiin joo, no käviskö ens viikonloppu? <juuh, okei <soittelen sit, moro >tässä kohti muistan vessapaperin >ei helvetti >ei saatana >ei jumalauta >muutama päivä aikaa  >käy siihen saakka päivittäin kaupassa, yhtenä päivänä jopa kaksi kertaa  >päättele, että n. 19:00 aikaan alkaa hiljeneä >tuomiopäivä >tule töistä vähän neljän jälkeen kotiin >pelaa dotaa sen minkä kerkeät pitääksesi mielesi pois asiasta >19:00 >lähde kauppaan, n. 20min matka kävellen (ei ole lähin kauppa) >kaupassa suhteellisen hiljaista, kassoja näytti olevan kaksi >ota ostoskori >täytä ostoskori kaikennäköisestä lanimätöstä >hillu sielä joku 15min "katselemassa mitä muuta ostaisi" >lopulta mene kotitalousosastolle >ota pieni 6 rullan pakkaus paskapaperia >kävelet nyt manuaalisesti kassalle >klassinen "kaksi vapaata kassaa" dilemma >toisessa istuu joku vanhempi rouva ja toisessa suunnilleen ikäiseni kassatyty >huokaise kevyesti helpotuksesta ja suuntaa kohti rouvan kassaa >asettele ensin mättö liukuhihnalle, sitten vessapaperi <voi teitä nuorukaisia... >syke nousee >tajua pienen hetken kuluttua, että hän kauhistelee mättöjäni <hei nuori mies, meiltä kuule löytyy nyt tätä peppupaperia alennuksestakin, samalla hinnalla saat kato 12 rullan peppupaperipakkauksen >hengittäminen muuttuu hankalaksi >saa juuri ja juuri sanottua edes jotain: "ai..." <hei tehdäänkö silleen et mä käyn hakemassa sulle sen, mä voin vinguttaa omaa plussakorttia jos sulla ei ole  >puhuminen edelleen vaikeaa >"..ei teidän..." <ei kun kato nyt on näin hiljasta, oota tässä vain pieni hetki niin säästät sinäkin katsos rahaa >ole paniikissa ja tajua, että sinun selän takanasi on edelleen se toinen kassatyty >huuda paniikissa "NE ON MUN ÄIDILLE!!!" >mitä vittua >juokse
    
    Kavereilleni sanoin, että olen kipeänä. Ne tuli sitten "yllätysvisiitille" jokatapauksessa ja kun eivät uskoneet, niin piti sitten selittää lopulta mistä on kyse. Nyt ne ostaa minulle vessapaperini.`,
    turkukissa: `Miuuuuuu, miuuuuuu kyl mä eile illal sit haisteli mamin tassui ku niis ol sen Roosan tuoksuu,
Miuuuuuu, no me kyl illal sit viel pelattii jalkkist ja leikittii kanttiksen kans, hrrrr
Miuuuuuu, yöl mä kipiti iha mamin kylkkee kii ja siin ja iha aamuu asti.
Miuuuuuuu, ja kehruukoneenki mä laito iha täysil.
Miuuuuuuu, ja voiha ihku ku ei mami ollu aamul minneskää kiirus ku me vaa olttii ja naatittii, hrrrr
Miuuuuu, no tietty ny vähä jossai mami kävi mut äkkii tul takas.
Miuuuuu, mut voiha peeteleen peetele ku mä hyppäsi ton tiskipöydäl nii siel oliki vettä ja pöh ja pöh ku mä kastuin,
Miuuuuuu, kyl siit sit paineli vikkelää ton sänkky al ja iha kaamee homma oli laittaa karvat kunttoo taas.
Miuuuuuuu, ja sit mami tiputti jottai ja tul iha kaamee ään ja taas mä sain kipittää sänkky al, pöh ja pöh.
Miuuuuuu, no huh huh mut ny me ootetaa sitä tanttii juttuu.
Miuuuuuu, ja täs kuvas mä oon eile valot pääl, hih hii`
}
